# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'NKSWRevealTemplate' do

pod 'SWRevealViewController', '~> 2.3.0'
pod 'AFNetworking', '~> 2.5.4'
pod 'MBProgressHUD', '~> 0.9.1'

end

